<a href="https://colab.research.google.com/github/Tanny-H/BSC_DPDM2025/blob/main/BSC_DPDM_Midterm_663020280_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Midterm วิชา Data Preprocessing and Data Mining
ผู้ทำ นายธนวุฒิ หาญเชิงชัย 663020280-8

##เตรียม Library

In [63]:
import pandas as pd
import numpy as np
from glob import glob

##เชื่อมต่อไดร์ฟ

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##นำเข้าไฟล์

In [64]:
hii_daily_rain = '/content/drive/MyDrive/bscdpdmmid25/Daily rain/hii_daily_rain.csv'
daily_rain_df = pd.read_csv(hii_daily_rain)

# Display the first 5 rows of the DataFrame
daily_rain_df.head(5)

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily

In [65]:
stations = '/content/drive/MyDrive/bscdpdmmid25/input/Stations in the model_HII.csv'
stations_df = pd.read_csv(stations)

# Display the first 5 rows of the DataFrame
stations_df.head()

   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

promt : 1.นำเข้าข้อมูลของinput ตั้งแต่07-12 2.ทำให้กระชับและชื่อพาร์ทสอดคล้องกัน

In [67]:
rain_files = glob(
    "/content/drive/MyDrive/bscdpdmmid25/input/2025-*/HII_daily_rainfall_*.csv"
)

print("Number of files:", len(rain_files))

Number of files: 184

In [68]:
rain_df = pd.concat(
    [pd.read_csv(f) for f in rain_files],
    ignore_index=True
)

promt : แสดงโครงสร้างข้อมูล

In [69]:
rain_df.info()
rain_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176886 entries, 0 to 176885
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       176886 non-null  object
 1   rainfall_datetime_calc  176886 non-null  object
 2   rainfall_value          176882 non-null  float64
 3   tele_station_id         173072 non-null  float64
 4   tele_station_oldcode    168021 non-null  object
 5   measure_datetime        176886 non-null  object
dtypes: float64(2), object(4)
memory usage: 8.1+ MB

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.0,13885.0,SWR018,2025-08-05
1,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.0,253.0,THAT,2025-08-05
2,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.0,315.0,KON003,2025-08-05
3,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.4,283.0,VLGE02,2025-08-05
4,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.0,447.0,THCG,2025-08-05

In [70]:
rain_df["source_file"] = rain_df.index

##สร้างคอลัมป์มาตรฐาน

In [73]:
rain_df["station"] = (
    rain_df["tele_station_oldcode"]
    .astype(str)
    .str.strip()
)

rain_df["rain"] = rain_df["rainfall_value"]

ตรวจสอบ

In [74]:
rain_df[["station", "rain"]].head()
rain_df["station"].nunique()

1515

##แปลงวันเวลา

In [75]:
rain_df["measure_datetime"] = pd.to_datetime(
    rain_df["measure_datetime"],
    errors="coerce"
)

In [76]:
rain_df["year"]  = rain_df["measure_datetime"].dt.year
rain_df["month"] = rain_df["measure_datetime"].dt.month
rain_df["day"]   = rain_df["measure_datetime"].dt.day
rain_df["doy"]   = rain_df["measure_datetime"].dt.dayofyear

Check sanity

In [77]:
print("Total records:", len(rain_df))
print("Stations:", rain_df["station"].nunique())
print("Date range:")
print(rain_df["measure_datetime"].min(), "→", rain_df["measure_datetime"].max())

Total records: 176886
Stations: 1515
Date range:
2025-07-01 00:00:00 → 2025-12-31 00:00:00

In [78]:
rain_df["station"].nunique()
rain_df["rain"].isna().sum()
rain_df.groupby("station").size().describe()

count    1515.000000
mean      116.756436
std       239.591916
min         1.000000
25%         3.000000
50%       177.000000
75%       184.000000
max      8865.000000
dtype: float64

In [79]:
missing_summary.describe()

       total_records  missing_records  missing_ratio
count     347.000000            347.0          347.0
mean        1.971182              0.0            0.0
std         0.167538              0.0            0.0
min         1.000000              0.0            0.0
25%         2.000000              0.0            0.0
50%         2.000000              0.0            0.0
75%         2.000000              0.0            0.0
max         2.000000              0.0            0.0

##กรองเฉพาะสถานีใน Stations in the model_HII.csv

In [102]:
stations_df = pd.read_csv(
    "/content/drive/MyDrive/bscdpdmmid25/input/Stations in the model_HII.csv"
)

stations_df.columns

Index(['Node', 'Lat', 'Long'], dtype='object')

In [104]:
stations_df = stations_df.rename(columns={"Node": "station"})
stations_df["station"] = stations_df["station"].astype(str).str.strip()

กรองข้อมูลฝน

In [105]:
before = rain_df["station"].nunique()

rain_df = rain_df[rain_df["station"].isin(stations_df["station"])]

after = rain_df["station"].nunique()

print("Stations before filtering:", before)
print("Stations after filtering :", after)

Stations before filtering: 829
Stations after filtering : 339

In [80]:
full_dates = pd.date_range(
    start="2025-07-01",
    end="2025-12-31",
    freq="D"
)

expected_days = len(full_dates)  # ≈ 184
expected_days

184

In [81]:
actual_days = (
    rain_df
    .groupby("station")["measure_datetime"]
    .nunique()
    .rename("actual_days")
)

##ระบุข้อมูลสูญหายของแต่ละสถานี

In [106]:
missing_summary = (
    rain_df
    .groupby("station")["rain"]
    .agg(
        total_records="size",
        missing_records=lambda x: x.isna().sum()
    )
)

missing_summary["missing_ratio"] = (
    missing_summary["missing_records"] /
    missing_summary["total_records"]
)

missing_summary.describe()

       total_records  missing_records  missing_ratio
count     339.000000            339.0          339.0
mean      182.404130              0.0            0.0
std         4.850314              0.0            0.0
min       149.000000              0.0            0.0
25%       184.000000              0.0            0.0
50%       184.000000              0.0            0.0
75%       184.000000              0.0            0.0
max       184.000000              0.0            0.0

In [82]:
missing_summary = pd.DataFrame({
    "actual_days": actual_days
})

missing_summary["expected_days"] = expected_days
missing_summary["missing_records"] = (
    missing_summary["expected_days"] -
    missing_summary["actual_days"]
)

missing_summary["missing_ratio"] = (
    missing_summary["missing_records"] /
    missing_summary["expected_days"]
)

missing_summary.describe()

       actual_days  expected_days  missing_records  missing_ratio
count  1515.000000         1515.0      1515.000000    1515.000000
mean    111.024422          184.0        72.975578       0.396606
std      82.612056            0.0        82.612056       0.448979
min       1.000000          184.0         0.000000       0.000000
25%       3.000000          184.0         0.000000       0.000000
50%     177.000000          184.0         7.000000       0.038043
75%     184.000000          184.0       181.000000       0.983696
max     184.000000          184.0       183.000000       0.994565

In [83]:
missing_summary.sort_values("missing_ratio", ascending=False).head(10)

         actual_days  expected_days  missing_records  missing_ratio
station
MOU098             1            184              183       0.994565
MOU003             1            184              183       0.994565
MOU047             1            184              183       0.994565
MOU177             1            184              183       0.994565
MOU182             1            184              183       0.994565
MOU190             1            184              183       0.994565
MOU167             1            184              183       0.994565
MOU256             1            184              183       0.994565
MOU282             1            184              183       0.994565
MOU292             1            184              183       0.994565

##คัดสถานีที่ missing ≥ 20% ออก

In [84]:
bad_stations = missing_summary[
    missing_summary["missing_ratio"] >= 0.20
].index

print("Stations removed:", len(bad_stations))

Stations removed: 686

In [85]:
rain_df = rain_df[~rain_df["station"].isin(bad_stations)]

print("Stations remaining:", rain_df["station"].nunique())

Stations remaining: 829

In [86]:
rain_df.groupby("station")["measure_datetime"].nunique().describe()

count    829.000000
mean     182.041013
std        5.830807
min      148.000000
25%      183.000000
50%      184.000000
75%      184.000000
max      184.000000
Name: measure_datetime, dtype: float64

##เติมข้อมูลด้วย Median ตาม Day of Year

In [87]:
median_doy = (
    rain_df
    .groupby(["station", "doy"])["rain"]
    .median()
)

เติม missing

In [88]:
def fill_median(row):
    if pd.isna(row["rain"]):
        return median_doy.get((row["station"], row["doy"]), np.nan)
    return row["rain"]

rain_df["rain"] = rain_df.apply(fill_median, axis=1)

/tmp/ipython-input-2814228172.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rain_df["rain"] = rain_df.apply(fill_median, axis=1)

ตรวจสอบ

In [89]:
rain_df["rain"].isna().sum()

np.int64(1)

ใช้ median ของสถานีนั้นแทน

In [90]:
station_median = rain_df.groupby("station")["rain"].median()

In [91]:
rain_df.loc[:, "rain"] = rain_df.apply(
    lambda row: (
        station_median[row["station"]]
        if pd.isna(row["rain"])
        else row["rain"]
    ),
    axis=1
)

ตรวบสอบ

In [92]:
rain_df["rain"].isna().sum()

np.int64(0)

##อภิปราย: เหตุผลที่เลือกใช้ Median แทน Mean ในการจัดการ Missing Data
ในการวิเคราะห์ข้อมูลปริมาณน้ำฝน พบว่าข้อมูลมีลักษณะการกระจายที่ ไม่เป็นแบบปกติ (non-normal distribution) กล่าวคือ ในหลายสถานีจะมีค่าปริมาณน้ำฝนเป็นศูนย์หรือมีค่าน้อยเป็นส่วนใหญ่ แต่บางวันอาจเกิดฝนตกหนักมาก ส่งผลให้มีค่าที่สูงผิดปกติ (outliers)

หากใช้ ค่าเฉลี่ย (Mean) ในการแทนค่าที่หายไป ค่าฝนที่สูงผิดปกติเหล่านี้จะดึงค่าเฉลี่ยให้สูงขึ้น ทำให้ค่าที่นำมาแทน ไม่สะท้อนพฤติกรรมปกติของข้อมูลจริง และอาจทำให้ผลการวิเคราะห์คลาดเคลื่อน

ค่ามัธยฐาน (Median) เป็นค่ากลางที่ไม่อ่อนไหวต่อ outliers จึงสามารถแทนค่าที่หายไปได้อย่างเหมาะสมกว่า โดยเฉพาะในข้อมูลปริมาณน้ำฝนซึ่งมีลักษณะเป็นข้อมูลเชิงสิ่งแวดล้อมที่มีความแปรปรวนสูง

## คำนวณผลรวมปริมาณน้ำฝนรายเดือน

In [93]:
monthly_df = (
    rain_df
    .groupby(["station", "year", "month"])["rain"]
    .sum()
    .reset_index()
)

In [94]:
monthly_df = monthly_df.rename(columns={"station": "Node"})
monthly_df = monthly_df[["Node", "rain", "month", "year"]]
monthly_df = monthly_df.sort_values(["Node", "year", "month"])

In [97]:
monthly_df.head()

   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

In [98]:
monthly_df.shape

(4972, 4)

In [100]:
from google.colab import files
files.download("output_monthly_rainfall.csv")

## LINK

[link google drive](https://drive.google.com/drive/folders/1ir9jiu48kn3s3ANPJoWv0_gQ5L7BIQZ-?usp=sharing)

[บันทึกการใช้AI](https://chatgpt.com/share/6971e42e-83f8-8003-baa1-72238b291571)